ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

VAGRANTFILE_API_VERSION = "2"

CURRENT_DIR = Dir.pwd

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "jenkins" do |web|
    web.vm.provider "docker" do |d|
      d.name = "s2jenkins"
      d.image = "jenkins:latest"
      d.ports = [ "8080:8080", "50000:50000" ]
      d.privileged = true
      d.volumes = [ CURRENT_DIR + "/jenkins_home:/var/jenkins_home" ]
    end
  end

end
